version: "3.4"

services:
  frontend:
    build:
      context: ./front
      target: production-stage
  cron:
    build:
      context: ./cron
  api:
    build:
      context: ./api
  reverse-proxy:
    build:
      context: ./reverse_proxy