version: "3.4"

services:
  db:
    ports:
      - "3306:3306"
  frontend:
    build:
      context: ./front
      target: development-stage
    volumes:
      - ./front:/app
  reverse-proxy:
    build:
      context: ./reverse_proxy
    environment:
      FRONTEND_PORT: 8080
  cron:
    build:
      context: ./cron
  api:
    build:
      context: ./api