version: "3.4"
services:
  db:
    image: mysql:8.0.25
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    volumes:
      - db_data:/var/lib/mysql
      - ./api/Database/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql:ro
    networks:
      - backend
    environment:
      MYSQL_DATABASE: alethia
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: zeus
      MYSQL_PASSWORD: kingOfGods
  redis_db:
    image: redis:6.2.4-alpine
    volumes:
      - redis_data:/data
    networks:
      - backend

  reverse-proxy:
    ports:
      - "80:80"
    image: tavakkoliamirmohmmad/alethia-reverse-proxy:v1.0
    networks:
      - reverse-proxy
    depends_on:
      - api
      - frontend
    environment:
      FRONTEND_NAME: frontend
      FRONTEND_PORT: 80
      API_NAME: api
      API_PORT: 3000
    restart: on-failure

  frontend:
    image: tavakkoliamirmohmmad/alethia-frontend:v1.0.1
    volumes:
      - /app/node_modules
    depends_on:
      - api
    networks:
      - reverse-proxy
    restart: on-failure
  api:
    image: tavakkoliamirmohmmad/alethia-api:v1.0.1
    networks:
      - backend
      - grpc
      - reverse-proxy
    depends_on:
      - db
      - redis_db
    environment:
      DB_USERNAME: zeus
      DB_PASSWORD: kingOfGods
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: alethia
      REDIS_HOST: redis_db
      REDIS_PORT: 6379
      REDIS_PASSWORD:
      GRPC_PORT: 7000
    restart: on-failure
  cron:
    image: tavakkoliamirmohmmad/alethia-birthday-cron:v1.0
    networks:
      - grpc
    depends_on:
      - api
      - db
      - redis_db
    restart: on-failure

networks:
  reverse-proxy:
    driver: bridge
  backend:
    driver: bridge
  grpc:
    driver: bridge

volumes:
  db_data:
  redis_data:
