version: "3.4"
services:
  db:
    image: mysql:8.0.25
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    volumes:
      - db_data:/var/lib/mysql
      - ./api/Database/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql:ro
    networks:
      - backend
    environment:
      MYSQL_DATABASE: alethia
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: zeus
      MYSQL_PASSWORD: kingOfGods
  redis_db:
    image: redis:6.2.4-alpine
    volumes:
      - redis_data:/data
    networks:
      - backend
  frontend:
    image: alethia_frontend:v0.01
    volumes:
      - /app/node_modules
    depends_on:
      - api
    environment:
      API_URL: api:3000
    restart: on-failure
  api:
    image: alethia_api:v0.01
    build:
      context: ./api
    networks:
      - backend
      - grpc
    depends_on:
      - db
      - redis_db
    environment:
      DB_USERNAME: zeus
      DB_PASSWORD: kingOfGods
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: alethia
      REDIS_HOST: redis_db
      REDIS_PORT: 6379
      REDIS_PASSWORD:
      GRPC_PORT: 7000
    restart: on-failure
  cron:
    image: alethia_cron_bd:v0.01
    build:
      context: ./cron
    networks:
      - grpc
    depends_on:
      - api
      - db
      - redis_db
    restart: on-failure
    
    

networks:
  backend:
    driver: bridge
  grpc:
    driver: bridge

volumes:
  db_data:
  redis_data:
