# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.birthday_pb2 as birthday__pb2


class BirthdayUpdaterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateInfos = channel.unary_unary(
                '/helloworld.BirthdayUpdater/UpdateInfos',
                request_serializer=birthday__pb2.BirthdayUpdateRequest.SerializeToString,
                response_deserializer=birthday__pb2.BirthdayUpdateResponse.FromString,
                )


class BirthdayUpdaterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateInfos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BirthdayUpdaterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateInfos': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateInfos,
                    request_deserializer=birthday__pb2.BirthdayUpdateRequest.FromString,
                    response_serializer=birthday__pb2.BirthdayUpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helloworld.BirthdayUpdater', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BirthdayUpdater(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateInfos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helloworld.BirthdayUpdater/UpdateInfos',
            birthday__pb2.BirthdayUpdateRequest.SerializeToString,
            birthday__pb2.BirthdayUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
